// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptionsDev {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcvC01V3hktvtSdhmbYD8LlLpd9CCs5ws',
    appId: '1:865759547472:web:e77541b0522af2fe9e0155',
    messagingSenderId: '865759547472',
    projectId: 'opensort-dev',
    authDomain: 'opensort-dev.firebaseapp.com',
    storageBucket: 'opensort-dev.appspot.com',
    measurementId: 'G-67K3XZM4P2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNi-quuEpzJsfmqtrMVwt12qUznhVWt8I',
    appId: '1:865759547472:android:f3d2f340e1593cf69e0155',
    messagingSenderId: '865759547472',
    projectId: 'opensort-dev',
    storageBucket: 'opensort-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuk-v4AaX6bq2EzZhitvy6Euas4jKYuL8',
    appId: '1:865759547472:ios:608057d0b558499a9e0155',
    messagingSenderId: '865759547472',
    projectId: 'opensort-dev',
    storageBucket: 'opensort-dev.appspot.com',
    iosClientId: '865759547472-m5k5ercrb5ojo7bmb1g43u6gpl66ek2e.apps.googleusercontent.com',
    iosBundleId: 'com.opensort.org',
  );
}
